### ISSUE TITLE
[Feature] Several xtra details

### ISSUE THREAD

**Issue by Mariusthvdb** [ngocjohn/lunar-phase#4]
### Short summary

https://api.ipgeolocation.io/astronomy provides some extra details?

### Detailed description

Hi, 
thanks for creating this integration, and your card! (got your link via the bio you mentioned in custom:button-card /-) )

Since this is not a bug report at all, please let me add below info as a FR. It's more of a FYI though, not requesting anything perse.

I noticed that your CC does not have a few of the interesting details the https://api.ipgeolocation.io/astronomy provides

I am using this rest:
```
rest:

  - resource: https://api.ipgeolocation.io/astronomy
    scan_interval: 1200
    params:
      apiKey: !secret ipgeolocation_api
      city: Roosendaal
#       country: Netherlands

    sensor:

      - unique_id: maan_astronomy
        value_template: >
          {{'Op' if value_json.moon_altitude > 0 else 'Onder'}}
        json_attributes:
          - date
          - current_time
          - sun_distance
          - moonrise
          - moonset
          - moon_status
          - moon_altitude # <-----
          - moon_distance
          - moon_azimuth # <-----
          - moon_parallactic_angle #<------
```

and have those extra details available.

Ive added them in a simple compound card like this:

<img width="498" alt="Scherm­afbeelding 2024-08-03 om 10 54 19" src="https://github.com/user-attachments/assets/b995e2ac-acdd-42bb-af24-63a151a854b6">

Figured you might want to know the availability and maybe add them to your CC's options.

thanks!
